# Phần 1: Khám phá Tensor

## Task 1.1

In [1]:
import torch
import numpy as np 

# Tạo tensor từ list
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(f"Tensor from data:\n{x_data}\n")

# Tạo tensor từ NumPy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(f"Tensor from NumPy array:\n{x_np}\n")

# Tạo tensor với các giá trị ngẫu nhiên hoặc hằng số
x_ones = torch.ones_like(x_data) # tạo tensor gồm các số 1 có cùng shape với x_data
print(f"Ones Tensor:\n{x_ones}\n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # tạo tensor ngẫu nhiên
print(f"Random Tensor:\n {x_rand}\n")
# In ra shape, dtype, và device của tensor
print(f"Shape của tensor: {x_rand.shape}")
print(f"Datatype của tensor: {x_rand.dtype}")
print(f"Device lưu trữ tensor: {x_rand.device}")

Tensor from data:
tensor([[1, 2],
        [3, 4]])

Tensor from NumPy array:
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

Ones Tensor:
tensor([[1, 1],
        [1, 1]])

Random Tensor:
 tensor([[0.3096, 0.0923],
        [0.2976, 0.9926]])

Shape của tensor: torch.Size([2, 2])
Datatype của tensor: torch.float32
Device lưu trữ tensor: cpu


## Task 1.2: Các phép toán trên Tensor

In [5]:
# 1. Cộng x_data với chính nó
sum_result = x_data + x_data
print(f"Cộng x_data với chính nó:\n{sum_result}\n")

# 2. Nhân x_data với 5
mul_result = x_data * 5
print(f"Nhân x_data với 5:\n{mul_result}\n")

# 3. Nhân ma trận x_data với x_data.T (ma trận chuyển vị của nó)
matmul_result = x_data @ x_data.T
print(f"Nhân ma trận x_data với x_data.T:\n{matmul_result}\n")

Cộng x_data với chính nó:
tensor([[2, 4],
        [6, 8]])

Nhân x_data với 5:
tensor([[ 5, 10],
        [15, 20]])

Nhân ma trận x_data với x_data.T:
tensor([[ 5, 11],
        [11, 25]])



## Task 1.3: Indexing và Slicing

In [6]:
# 1. Lấy ra hàng đầu tiên
first_row = x_data[0]
print(f"Hàng đầu tiên của x_data: {first_row}")

# 2. Lấy ra cột thứ hai
second_col = x_data[:, 1]
print(f"Cột thứ hai của x_data: {second_col}")

# 3. Lấy ra giá trị ở hàng thứ hai, cột thứ hai
value_2_2 = x_data[1, 1]
print(f"Giá trị ở hàng 2, cột 2 của x_data: {value_2_2}")

Hàng đầu tiên của x_data: tensor([1, 2])
Cột thứ hai của x_data: tensor([2, 4])
Giá trị ở hàng 2, cột 2 của x_data: 4


## Task 1.4: Thay đổi hình dạng Tensor

In [9]:
# Tạo một tensor ngẫu nhiên có shape (4, 4)
tensor_4x4 = torch.rand(4, 4)
print(f"Tensor shape (4, 4):\n{tensor_4x4}\n")

# Dùng view để biến thành shape (16, 1)
tensor_16x1 = tensor_4x4.view(16, 1)
print(f"Tensor shape (16, 1) dùng view:\n{tensor_16x1}\n")

# Hoặc dùng reshape (kết quả tương tự)
tensor_16x1_reshape = tensor_4x4.reshape(16, 1)
print(f"Tensor shape (16, 1) dùng reshape:\n{tensor_16x1_reshape}")

Tensor shape (4, 4):
tensor([[0.3617, 0.6837, 0.9762, 0.0829],
        [0.1719, 0.4431, 0.5921, 0.4091],
        [0.7341, 0.0572, 0.6389, 0.9127],
        [0.2222, 0.6200, 0.1820, 0.2217]])

Tensor shape (16, 1) dùng view:
tensor([[0.3617],
        [0.6837],
        [0.9762],
        [0.0829],
        [0.1719],
        [0.4431],
        [0.5921],
        [0.4091],
        [0.7341],
        [0.0572],
        [0.6389],
        [0.9127],
        [0.2222],
        [0.6200],
        [0.1820],
        [0.2217]])

Tensor shape (16, 1) dùng reshape:
tensor([[0.3617],
        [0.6837],
        [0.9762],
        [0.0829],
        [0.1719],
        [0.4431],
        [0.5921],
        [0.4091],
        [0.7341],
        [0.0572],
        [0.6389],
        [0.9127],
        [0.2222],
        [0.6200],
        [0.1820],
        [0.2217]])


# Phần 2: Tự động tính Đạo hàm với autograd

## Task 2.1: Thực hành với autograd

In [14]:
# Tạo một tensor và yêu cầu tính đạo hàm cho nó
x = torch.ones(1, requires_grad=True)
print(f"x: {x}")

# Thực hiện một phép toán
y = x + 2
print(f"y: {y}")

# y được tạo ra từ một phép toán có x, nên nó cũng có grad_fn
print(f"grad_fn của y: {y.grad_fn}")

# Thực hiện thêm các phép toán
z = y * y * 3

# Tính đạo hàm của z theo x
z.backward(retain_graph=True) # tương đương z.backward(torch.tensor(1.))

# Đạo hàm được lưu trong thuộc tính .grad
# Ta có z = 3 * (x+2)^2 => dz/dx = 6 * (x+2). Với x=1, dz/dx = 18
print(f"Đạo hàm của z theo x: {x.grad}")

## Câu hỏi: Chuyện gì xảy ra nếu bạn gọi z.backward() một lần nữa? Tại sao?
# Nếu bạn gọi z.backward() một lần nữa mà không truyền thêm đối số nào, sẽ xuất hiện lỗi:
# RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). 
# Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). 
# Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.
# Lý do: Sau lần gọi backward() đầu tiên, đồ thị tính toán (computation graph) mặc định bị giải phóng để tiết kiệm bộ nhớ.
# Nếu muốn gọi backward() nhiều lần trên cùng một đồ thị, bạn cần truyền thêm retain_graph=True như sau:
z.backward() 
print(f"Đạo hàm của z theo x sau lần backward thứ hai: {x.grad}")

x: tensor([1.], requires_grad=True)
y: tensor([3.], grad_fn=<AddBackward0>)
grad_fn của y: <AddBackward0 object at 0x0000017077C11450>
Đạo hàm của z theo x: tensor([18.])
Đạo hàm của z theo x sau lần backward thứ hai: tensor([36.])


# Phần 3: Xây dựng Mô hình đầu tiên với torch.nn

## Task 3.1: Lớp nn.Linear

In [4]:
# Khởi tạo một lớp Linear biến đổi từ 5 chiều -> 2 chiều
linear_layer = torch.nn.Linear(in_features=5, out_features=2)

# Tạo một tensor đầu vào mẫu
input_tensor = torch.randn(3, 5) # 3 mẫu, mỗi mẫu 5 chiều

# Truyền đầu vào qua lớp linear
output = linear_layer(input_tensor)
print(f"Input shape: {input_tensor.shape}")
print(f"Output shape: {output.shape}")
print(f"Output:\n {output}")

Input shape: torch.Size([3, 5])
Output shape: torch.Size([3, 2])
Output:
 tensor([[-0.0814, -0.5549],
        [-0.4962, -0.7947],
        [ 0.2801, -0.0429]], grad_fn=<AddmmBackward0>)


## Task 3.2: Lớp nn.Embedding

In [7]:
# Khởi tạo lớp Embedding cho một từ điển 10 từ, mỗi từ biểu diễn bằng vector 3 chiều
embedding_layer = torch.nn.Embedding(num_embeddings=10, embedding_dim=3)

# Tạo một tensor đầu vào chứa các chỉ số của từ (ví dụ: một câu)
# Các chỉ số phải nhỏ hơn 10
input_indices = torch.LongTensor([1, 5, 0, 8])

# Lấy ra các vector embedding tương ứng
embeddings = embedding_layer(input_indices)
print(f"Input shape: {input_indices.shape}")
print(f"Output shape: {embeddings.shape}")
print(f"Embeddings:\n {embeddings}")

Input shape: torch.Size([4])
Output shape: torch.Size([4, 3])
Embeddings:
 tensor([[ 0.6770, -0.0210,  0.4555],
        [ 0.6287,  0.0908, -0.6921],
        [ 0.6627,  0.2312, -1.1661],
        [-0.2540, -0.6303, -0.1210]], grad_fn=<EmbeddingBackward0>)


## Task 3.3: Kết hợp thành một nn.Module

In [15]:
from torch import nn
class MyFirstModel(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim):
        super(MyFirstModel, self).__init__()
        # Định nghĩa các lớp (layer) bạn sẽ dùng
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.linear = nn.Linear(embedding_dim, hidden_dim)
        self.activation = nn.ReLU() # Hàm kích hoạt
        self.output_layer = nn.Linear(hidden_dim, output_dim)

    def forward(self, indices):
        # Định nghĩa luồng dữ liệu đi qua các lớp
        # 1. Lấy embedding
        embeds = self.embedding(indices)
        # 2. Truyền qua lớp linear và hàm kích hoạt
        hidden = self.activation(self.linear(embeds))
        # 3. Truyền qua lớp output
        output = self.output_layer(hidden)
        return output
    
# Khởi tạo và kiểm tra mô hình
model = MyFirstModel(vocab_size=100, embedding_dim=16, hidden_dim=8, output_dim=2)
input_data = torch.LongTensor([[1, 2, 5, 9]]) # một câu gồm 4 từ

output_data = model(input_data)
print(f"Model output shape: {output_data.shape}")

Model output shape: torch.Size([1, 4, 2])
